// ze_FFXII_Mt_Bur_Omisace_v6_beta6 item text script by koen (STEAM_1:1:114921174)
// DO NOT JUDGE ME FOR HOW SHIT THESE SCRIPTS ARE (╯°□°)╯︵ ┻━┻

// HEAL TEXT
heal_text <- [
	"ITEM - CURE MAGICK\nEFFECT - HEALS NEARBY HUMANS\nDURATION - 5 SECONDS\nCOOLDOWN - 75 SECONDS\nITEM LEVEL - 1",
	"ITEM - CURA MAGICK\nEFFECT - HEALS NEARBY HUMANS\nDURATION - 5 SECONDS\nCOOLDOWN - 75 SECONDS\nITEM LEVEL - 2",
	"ITEM - CURAGA MAGICK\nEFFECT - HEALS NEARBY HUMANS\nDURATION - 5 SECONDS\nCOOLDOWN - 75 SECONDS\nITEM LEVEL - 3",
	"ITEM - CURABA MAGICK\nEFFECT - HEALS NEARBY HUMANS\nDURATION - 5 SECONDS\nCOOLDOWN - 75 SECONDS\nITEM LEVEL - 4",
	"ITEM - RESTORATION MAGICK\nEFFECT - HEALS NEARBY HUMANS\nDURATION - 5 SECONDS\nCOOLDOWN - 75 SECONDS\nITEM LEVEL - 5"
];

function PrintHealText(iNum)
{
	self.__KeyValueFromString("message", heal_text[iNum - 1]);
	EntFireByHandle(self, "Display", "", 0.1, activator, null);
}

// SAND TEXT
sand_text <- [
	"ITEM - SAND MAGICK\nEFFECT - PULLS NEARBY ZOMBIES\nDURATION - 4 SECONDS\nCOOLDOWN - 75 SECONDS\nITEM LEVEL - 1",
	"ITEM - SANDRA MAGICK\nEFFECT - PULLS NEARBY ZOMBIES\nDURATION - 5 SECONDS\nCOOLDOWN - 75 SECONDS\nITEM LEVEL - 2",
	"ITEM - SANDGA MAGICK\nEFFECT - PULLS NEARBY ZOMBIES\nDURATION - 6 SECONDS\nCOOLDOWN - 75 SECONDS\nITEM LEVEL - 3",
	"ITEM - SANDBA MAGICK\nEFFECT - PULLS NEARBY ZOMBIES\nDURATION - 6 SECONDS\nCOOLDOWN - 75 SECONDS\nITEM LEVEL - 4",
	"ITEM - NATURE'S EMBRACE MAGICK\nEFFECT - PULLS NEARBY ZOMBIES\nDURATION - 7 SECONDS\nCOOLDOWN - 75 SECONDS\nITEM LEVEL - 5"
];

function PrintSandText(iNum)
{
	self.__KeyValueFromString("message", sand_text[iNum - 1]);
	EntFireByHandle(self, "Display", "", 0.1, activator, null);
}

// THUNDER TEXT
thunder_text <- [
	"ITEM - THUNDER MAGICK\nEFFECT - DAMAGES & SLOWS ZOMBIES\nDURATION - 5 SECONDS\nCOOLDOWN - 75 SECONDS\nITEM LEVEL - 1",
	"ITEM - THUNDARA MAGICK\nEFFECT - DAMAGES & SLOWS ZOMBIES\nDURATION - 6 SECONDS\nCOOLDOWN - 75 SECONDS\nITEM LEVEL - 2",
	"ITEM - THUNDAGA MAGICK\nEFFECT - DAMAGES & SLOWS ZOMBIES\nDURATION - 7 SECONDS\nCOOLDOWN - 75 SECONDS\nITEM LEVEL - 3",
	"ITEM - THUNDBA MAGICK\nEFFECT - DAMAGES & SLOWS ZOMBIES\nDURATION - 8 SECONDS\nCOOLDOWN - 75 SECONDS\nITEM LEVEL - 4",
	"ITEM - RAGE OF THE SKIES MAGICK\nEFFECT - DAMAGES & SLOWS ZOMBIES\nDURATION - 9 SECONDS\nCOOLDOWN - 75 SECONDS\nITEM LEVEL - 5"
];

function PrintThunderText(iNum)
{
	self.__KeyValueFromString("message", thunder_text[iNum - 1]);
	EntFireByHandle(self, "Display", "", 0.1, activator, null);
}

// FIRE TEXT
fire_text <- [
	"ITEM - FIRE MAGICK\nEFFECT - IGNITES NEARBY ZOMBIES\nDURATION - 4 SECONDS\nCOOLDOWN - 75 SECONDS\nITEM LEVEL - 1",
	"ITEM - FIRA MAGICK\nEFFECT - IGNITES NEARBY ZOMBIES\nDURATION - 5 SECONDS\nCOOLDOWN - 75 SECONDS\nITEM LEVEL - 2",
	"ITEM - FIRAGA MAGICK\nEFFECT - IGNITES NEARBY ZOMBIES\nDURATION - 6 SECONDS\nCOOLDOWN - 75 SECONDS\nITEM LEVEL - 3",
	"ITEM - FIREBA MAGICK\nEFFECT - IGNITES NEARBY ZOMBIES\nDURATION - 7 SECONDS\nCOOLDOWN - 75 SECONDS\nITEM LEVEL - 4",
	"ITEM - INFERNO MAGICK\nEFFECT - IGNITES NEARBY ZOMBIES\nDURATION - 8 SECONDS\nCOOLDOWN - 75 SECONDS\nITEM LEVEL - 5"
];

function PrintFireText(iNum)
{
	self.__KeyValueFromString("message", fire_text[iNum - 1]);
	EntFireByHandle(self, "Display", "", 0.1, activator, null);
}

// DARK TEXT
dark_text <- [
	"ITEM - DARK MAGICK\nEFFECT - SLOWS NEARBY ZOMBIES\nDURATION - 4 SECONDS\nCOOLDOWN - 75 SECONDS\nITEM LEVEL - 1",
	"ITEM - DARKRA MAGICK\nEFFECT - SLOWS NEARBY ZOMBIES\nDURATION - 5 SECONDS\nCOOLDOWN - 75 SECONDS\nITEM LEVEL - 2",
	"ITEM - DARKGA MAGICK\nEFFECT - SLOWS NEARBY ZOMBIES\nDURATION - 6 SECONDS\nCOOLDOWN - 75 SECONDS\nITEM LEVEL - 3",
	"ITEM - DARKBA MAGICK\nEFFECT - SLOWS NEARBY ZOMBIES\nDURATION - 7 SECONDS\nCOOLDOWN - 75 SECONDS\nITEM LEVEL - 4",
	"ITEM - ETERNAL DARKNESS MAGICK\nEFFECT - SLOWS NEARBY ZOMBIES\nDURATION - 7 SECONDS\nCOOLDOWN - 75 SECONDS\nITEM LEVEL - 5"
];

function PrintDarkText(iNum)
{
	self.__KeyValueFromString("message", dark_text[iNum - 1]);
	EntFireByHandle(self, "Display", "", 0.1, activator, null);
}

// HASTE TEXT
haste_text <- [
	"ITEM - HASTE MAGICK\nEFFECT - GIVES SPEED BOOST TO NEARBY HUMANS\nDURATION - 2 SECONDS\nCOOLDOWN - 75 SECONDS\nITEM LEVEL - 1",
	"ITEM - HASTERA MAGICK\nEFFECT - GIVES SPEED BOOST TO NEARBY HUMANS\nDURATION - 3 SECONDS\nCOOLDOWN - 75 SECONDS\nITEM LEVEL - 2",
	"ITEM - HASTAGA MAGICK\nEFFECT - GIVES SPEED BOOST TO NEARBY HUMANS\nDURATION - 4 SECONDS\nCOOLDOWN - 75 SECONDS\nITEM LEVEL - 3",
	"ITEM - HASTEBA MAGICK\nEFFECT - GIVES SPEED BOOST TO NEARBY HUMANS\nDURATION - 5 SECONDS\nCOOLDOWN - 75 SECONDS\nITEM LEVEL - 4",
	"ITEM - DREAMWALKER MAGICK\nEFFECT - GIVES SPEEDBOOST TO NEARBY HUMANS\nDURATION - 6 SECONDS\nCOOLDOWN - 75 SECONDS\nITEM LEVEL - 5"
];

function PrintHasteText(iNum)
{
	self.__KeyValueFromString("message", haste_text[iNum - 1]);
	EntFireByHandle(self, "Display", "", 0.1, activator, null);
}

// LIMIT TEXT
limit_text <- [
	"ITEM - LIMIT BREAK MAGICK\nEFFECT - SUMMONS A BEAST WITH UNLIMITED POWER\nDURATION - ? ? ?\nCOOLDOWN - 75 SECONDS\nITEM LEVEL - 1",
	"ITEM - LIMIT BREAK MAGICK\nEFFECT - SUMMONS A BEAST WITH UNLIMITED POWER\nDURATION - ? ? ?\nCOOLDOWN - ONLY 1 USE\nITEM LEVEL - 2",
	"ITEM - LIMIT BREAK MAGICK\nEFFECT - SUMMONS A BEAST WITH UNLIMITED POWER\nDURATION - ? ? ?\nCOOLDOWN - ONLY 1 USE\nITEM LEVEL - 3",
	"ITEM - LIMIT BREAK MAGICK\nEFFECT - SUMMONS A BEAST WITH UNLIMITED POWER\nDURATION - ? ? ?\nCOOLDOWN - ONLY 1 USE\nITEM LEVEL - 4",
	"ITEM - LIMIT BREAK MAGICK\nEFFECT - SUMMONS A BEAST WITH UNLIMITED POWER\nDURATION - ? ? ?\nCOOLDOWN - ONLY 1 USE\nITEM LEVEL - 5"
];

function PrintLimitText(iNum)
{
	self.__KeyValueFromString("message", limit_text[iNum - 1]);
	EntFireByHandle(self, "Display", "", 0.1, activator, null);
}

// AQUA TEXT
aqua_text <- [
	"ITEM - AQUA MAGICK\nEFFECT - PUSHES ZOMBIES IN A STRAIGHT LINE\nDURATION - 2 SECONDS\nCOOLDOWN - 75 SECONDS\nITEM LEVEL - 1",
	"ITEM - AQUARA MAGICK\nEFFECT - SLOWS ZOMBIES IN A STRAIGHT LINE\nDURATION - 5 SECONDS\nCOOLDOWN - 75 SECONDS\nITEM LEVEL - 2",
	"ITEM - AQUAGA MAGICK\nEFFECT - SLOWS NEARBY ZOMBIES\nDURATION - 7 SECONDS\nCOOLDOWN - 75 SECONDS\nITEM LEVEL - 3",
	"ITEM - AQUABA MAGICK\nEFFECT - SLOWS NEARBY ZOMBIES\nDURATION - 8 SECONDS\nCOOLDOWN - 75 SECONDS\nITEM LEVEL - 4",
	"ITEM - LEVIATHAN MAGICK\nEFFECT - SLOWS NEARBY ZOMBIES\nDURATION - 9 SECONDS\nCOOLDOWN - 75 SECONDS\nITEM LEVEL - 5"
];

function PrintAquaText(iNum)
{
	self.__KeyValueFromString("message", aqua_text[iNum - 1]);
	EntFireByHandle(self, "Display", "", 0.1, activator, null);
}

// SKIN ITEM TEXT
skin_items <- [
	"JUDGE BERGAN\n[M1] AXE (65 SECOND COOLDOWN)\n[M2] SOMETHING (60 SECOND COOLDOWN)",
	"JUDGE DRACE\n[M1] POISON SHIELD (65 SECOND COOLDOWN)\n[M2] SUMMON PLAGUE (60 SECOND COOLDOWN)",
	"JUDGE GABRANTH\n[M1] SPEED BOOST (65 SECOND COOLDOWN)\n[M2] PUSH AND DAMAGE HUMANS (65 SECOND COOLDOWN)",
	"JUDGE ZARGABAATH\n[M1] DAMAGE NEARBY HUMANS (60 SECOND COOLDOWN)\n[M2] USE MAIN WEAPON (65 SECOND COOLDOWN)"
];

function PrintSkinText(iNum)
{
	self.__KeyValueFromString("message", skin_items[iNum]);
	EntFireByHandle(self, "Display", "", 0.1, activator, null);
}

// MISC ITEMS
misc_items <- [
	"ITEM - GUNBLADE\nEFFECT - DAMAGES ALL TOUCHED ZOMBIES\nDURATION - 3 SECONDS\nCOOLDOWN - 75 SECONDS",
	"ITEM - UNDERWORLD ROD\nEFFECT - SUMMONS A PLAGUE THAT DESTROYS ALL IN ITS WAY\nDURATION - 5 SECONDS\nCOOLDOWN - 75 SECONDS",
	"ITEM - HEAL POTION\nEFFECT - HEALS NEARBY HUMANS TEMPORARILY\nDURATION - 3 SECONDS\nCOOLDOWN - ONLY 1 USE",
	"ITEM - MANA POTION\nEFFECT - GIVES AMMO TO NEARBY HUMANS\nDURATION - 2 SECONDS\nCOOLDOWN - ONLY 1 USE",
	"ITEM - SWORD OF KINGS\nEFFECT - DOUBLES DAMAGE DONE TO BOSSES\nDURATION - 4 SECONDS\nCOOLDOWN - ONLY 1 USE",
	"ITEM - ULTIMATE BLADE\nEFFECT - GIVES AMMO TO NEARBY HUMANS\nDURATION - 4 SECONDS\nCOOLDOWN - ONLY 1 USE"
];

function PrintMiscText(iNum)
{
	self.__KeyValueFromString("message", misc_items[iNum]);
	EntFireByHandle(self, "Display", "", 0.1, activator, null);
}

// SHIELD TEXT
shield_text <- [
	"ITEM - ENSANGUINED SHIELD\nEFFECT - A SHIELD THAT BLOCKS ZOMBIES\nDURATION - 2 SECONDS\nCOOLDOWN - 75 SECONDS\nITEM LEVEL - 1",
	"ITEM - ENSANGUINED SHIELD\nEFFECT - A SHIELD THAT BLOCKS ZOMBIES\nDURATION - 3 SECONDS\nCOOLDOWN - 75 SECONDS\nITEM LEVEL - 2",
	"ITEM - ENSANGUINED SHIELD\nEFFECT - A SHIELD THAT BLOCKS ZOMBIES\nDURATION - 4 SECONDS\nCOOLDOWN - 75 SECONDS\nITEM LEVEL - 3",
	"ITEM - ENSANGUINED SHIELD\nEFFECT - A SHIELD THAT BLOCKS ZOMBIES\nDURATION - 5 SECONDS\nCOOLDOWN - 75 SECONDS\nITEM LEVEL - 4",
	"ITEM - ENSANGUINED SHIELD\nEFFECT - A SHIELD THAT BLOCKS ZOMBIES\nDURATION - 6 SECONDS\nCOOLDOWN - 75 SECONDS\nITEM LEVEL - 5"
];

function PrintShieldText(iNum)
{
	self.__KeyValueFromString("message", shield_text[iNum - 1]);
	EntFireByHandle(self, "Display", "", 0.1, activator, null);
}

// ZOMBIE DARK
zombie_dark_text <- [
	"ITEM - DARK MAGICK\nEFFECT - PULLS SURROUNDING HUMANS TO THE CENTER\nDURATION - 2 SECONDS\nCOOLDOWN - 65 SECONDS\nITEM LEVEL - 1",
	"ITEM - DARKRA MAGICK\nEFFECT - PULLS SURROUNDING HUMANS TO THE CENTER\nDURATION - 3 SECONDS\nCOOLDOWN - 65 SECONDS\nITEM LEVEL - 2",
	"ITEM - DARKGA MAGICK\nEFFECT - PULLS SURROUNDING HUMANS TO THE CENTER\nDURATION - 4 SECONDS\nCOOLDOWN - 65 SECONDS\nITEM LEVEL - 3",
	"ITEM - DARKGA MAGICK\nEFFECT - PULLS SURROUNDING HUMANS TO THE CENTER\nDURATION - 5 SECONDS\nCOOLDOWN - 65 SECONDS\nITEM LEVEL - 4",
	"ITEM - ETERNAL DARKNESS MAGICK\nEFFECT - PULLS SURROUNDING HUMANS TO THE CENTER\nDURATION - 6 SECONDS\nCOOLDOWN - 65 SECONDS\nITEM LEVEL - 5"
];

function PrintZombieDarkText(iNum)
{
	self.__KeyValueFromString("message", zombie_dark_text[iNum - 1]);
	EntFireByHandle(self, "Display", "", 0.1, activator, null);
}

// ZOMBIE FEAR
zombie_fear_text <- [
	"ITEM - FEAR MAGICK\nEFFECT - FREEZES NEARBY HUMANS\nDURATION - MOMENTARY\nCOOLDOWN - 65 SECONDS\nITEM LEVEL - 1",
	"ITEM - HELLFORGED VOICE MAGICK\nEFFECT - FREEZES NEARBY HUMANS\nDURATION - MOMENTARY\nCOOLDOWN - 65 SECONDS\nITEM LEVEL - 2",
	"ITEM - DREADED REAPER MAGICK\nEFFECT - FREEZES NEARBY HUMANS\nDURATION - MOMENTARY\nCOOLDOWN - 65 SECONDS\nITEM LEVEL - 3",
	"ITEM - BEASTSLAYER MAGICK\nEFFECT - FREEZES NEARBY HUMANS\nDURATION - MOMENTARY\nCOOLDOWN - 65 SECONDS\nITEM LEVEL - 4",
	"ITEM - SOULDSHREDDER MAGICK\nEFFECT - FREEZES NEARBY HUMANS\nDURATION - MOMENTARY\nCOOLDOWN - 65 SECONDS\nITEM LEVEL - 5"
];

function PrintZombieFearText(iNum)
{
	self.__KeyValueFromString("message", zombie_fear_text[iNum - 1]);
	EntFireByHandle(self, "Display", "", 0.1, activator, null);
}

// ZOMBIE DAMAGE
zombie_damage_text <- [
	"ITEM - DAMAGE MAGICK\nEFFECT - DAMAGES NEARBY HUMANS\nDURATION - MOMENTARY\nCOOLDOWN - 65 SECONDS\nITEM LEVEL - 1",
	"ITEM - DAMAGSA MAGICK\nEFFECT - DAMAGES NEARY HUMANS\nDURATION - MOMENTARY\nCOOLDOWN - 65 SECONDS\nITEM LEVEL - 2",
	"ITEM - DAMAGA MAGICK\nEFFECT - DAMAGES NEARBY HUMANS\nDURATION - MONENTARY\nCOOLDOWN - 65 SECONDS\nITEM LEVEL - 3",
	"ITEM - DAMABA MAGICK\nEFFECT - DAMAGES NEARBY HUMANS\nDURATION - MOMENTARY\nCOOLDOWN - 65 SECONDS\nITEM LEVEL - 4",
	"ITEM - THE AVENGER MAGICK\nEFFECT - DAMAGES NEARBY HUMANS\nDURATION - MOMENTARY\nCOOLDOWN - 65 SECONDS\nITEM LEVEL - 5"
]

function PrintZombieDamageText(iNum)
{
	self.__KeyValueFromString("message", zombie_damage_text[iNum - 1]);
	EntFireByHandle(self, "Display", "", 0.1, activator, null);
}

// WIND
wind_text <- [
	"ITEM - AERO MAGICK\nEFFECT - MAKES A TORNADO THAT PUSHES NEARBY ZOMBIES AWAY\nDURATION - 4 SECONDS\nCOOLDOWN - 75 SECONDS\nITEM LEVEL - 1",
	"ITEM - AERAGA MAGICK\nEFFECT - MAKES A TORNADO THAT PUSHES NEARBY ZOMBIES AWAY\nDURATION - 5 SECONDS\nCOOLDOWN - 75 SECONDS\nITEM LEVEL - 2",
	"ITEM - AERAGA MAGICK\nEFFECT - MAKES A TORNADO THAT PUSHES NEARBY ZOMBIES AWAY\nDURATION - 6 SECONDS\nCOOLDOWN - 75 SECONDS\nITEM LEVEL - 3",
	"ITEM - AEROBA MAGICK\nEFFECT - MAKES A TORNADO THAT PUSHES NEARBY ZOMBIES AWAY\nDURATION - 7 SECONDS\nCOOLDOWN - 75 SECONDS\nITEM LEVEL - 4",
	"ITEM - WIND STORM MAGICK\nEFFECT - MAKES A TORNADO THAT PUSHES NEARBY ZOMBIES AWAY\nDURATION - 8 SECONDS\nCOOLDOWN - 75 SECONDS\nITEM LEVEL - 5"
];

function PrintWindText(iNum)
{
	self.__KeyValueFromString("message", wind_text[iNum - 1]);
	EntFireByHandle(self, "Display", "", 0.1, activator, null);
}

// OIL
oil_text <- [
	"ITEM - OIL MAGICK\nEFFECT - STICKS ZOMBIES TO THE FLOOR\nDURATION - 6 SECONDS\nCOOLDOWN - 75 SECONDS\nITEM LEVEL - 1",
	"ITEM - OILA MAGICK\nEFFECT - STICKS ZOMBIES TO THE FLOOR\nDURATION - 7 SECONDS\nCOOLDOWN - 75 SECONDS\nITEM LEVEL - 2",
	"ITEM - OILAGA MAGICK\nEFFECT - STICKS ZOMBIES TO THE FLOOR\nDURATION - 8 SECONDS\nCOOLDOWN - 75 SECONDS\nITEM LEVEL - 3",
	"ITEM - OILBA MAGICK\nEFFECT - STICKS ZOMBIES TO THE FLOOR\nDURATION - 9 SECONDS\nCOOLDOWN - 75 SECONDS\nITEM LEVEL - 4",
	"ITEM - SPECTRAL DIMENSIONS MAGICK\nEFFECT - STICKS ZOMBIES TO THE FLOOR\nDURATION - 10 SECONDS\nCOOLDOWN - 75 SECONDS\nITEM LEVEL - 5"
];

function PrintOilText(iNum)
{
	self.__KeyValueFromString("message", oil_text[iNum - 1]);
	EntFireByHandle(self, "Display", "", 0.1, activator, null);
}

// CROSSBOW TEXT
crossbow_text <- [
	"ITEM - CROSSBOW\nDURATION - 2 SECONDS\nCOOLDOWN - 4 SECONDS\nITEM LEVEL - 1",
	"ITEM - UMBRAL CROSSBOW\nDURATION - 2 SECONDS\nCOOLDOWN - 4 SECONDS\nITEM LEVEL - 2",
	"ITEM - COBRA CROSSBROW\nDURATION - 2 SECONDS\nCOOLDOWN - 4 SECONDS\nITEM LEVEL - 3",
	"ITEM - THE DEVIL EYE\nDURATION - 2 SECONDS\nCOOLDOWN - 4 SECONDS\nITEM LEVEL - 4",
	"ITEM - CHAIN BOLTER\nDURATION - 2 SECONDS\nCOOLDOWN - 4 SECONDS\nITEM LEVEL - 5"
];

function PrintCrossbowText(iNum)
{
	self.__KeyValueFromString("message", crossbow_text[iNum - 1]);
	EntFireByHandle(self, "Display", "", 0.1, activator, null);
}
